name: CI/CD - Build and Deploy Slackbot

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Deploy to Render
        env:
          RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}
        run: |
          curl -X POST $RENDER_DEPLOY_HOOK

      # OPTIONAL: Trigger Jenkins job (commented out, use if needed)
      # - name: Trigger Jenkins Job
      #   env:
      #     JENKINS_URL: ${{ secrets.JENKINS_URL }}
      #     JENKINS_USER: ${{ secrets.JENKINS_USER }}
      #     JENKINS_TOKEN: ${{ secrets.JENKINS_TOKEN }}
      #   run: |
      #     curl -X POST "$JENKINS_URL/job/YOUR_JOB_NAME/build?token=$JENKINS_TOKEN" \
      #       --user $JENKINS_USER:$JENKINS_TOKEN
